

insert into grid(id, css_id) values(0, 'r1c4');
insert into grid(id, css_id) values(1, 'r1c12');
insert into grid(id, css_id) values(2, 'r2c4');
insert into grid(id, css_id) values(3, 'r2c5');
insert into grid(id, css_id) values(4, 'r2c11');
insert into grid(id, css_id) values(5, 'r2c12');
insert into grid(id, css_id) values(6, 'r3c4');
insert into grid(id, css_id) values(7, 'r3c5');
insert into grid(id, css_id) values(8, 'r3c10');
insert into grid(id, css_id) values(9, 'r3c11');
insert into grid(id, css_id) values(10,'r3c12');
insert into grid(id, css_id) values(11, 'r4c4');
insert into grid(id, css_id) values(12, 'r4c5');
insert into grid(id, css_id) values(13, 'r4c6');
insert into grid(id, css_id) values(14, 'r4c10');
insert into grid(id, css_id) values(15, 'r4c11');
insert into grid(id, css_id) values(16, 'r4c12');
insert into grid(id, css_id) values(17, 'r5c4');
insert into grid(id, css_id) values(18, 'r5c5');
insert into grid(id, css_id) values(19, 'r5c6');
insert into grid(id, css_id) values(20, 'r5c10');
insert into grid(id, css_id) values(21, 'r5c11');
insert into grid(id, css_id) values(22, 'r5c12');
insert into grid(id, css_id) values(23, 'r6c4');
insert into grid(id, css_id) values(24, 'r6c5');
insert into grid(id, css_id) values(25, 'r6c6');
insert into grid(id, css_id) values(26, 'r6c7');
insert into grid(id, css_id) values(27, 'r6c9');
insert into grid(id, css_id) values(28, 'r6c10');
insert into grid(id, css_id) values(29, 'r6c11');
insert into grid(id, css_id) values(30, 'r6c12');
insert into grid(id, css_id) values(31, 'r7c4');
insert into grid(id, css_id) values(32, 'r7c5');
insert into grid(id, css_id) values(33, 'r7c6');
insert into grid(id, css_id) values(34, 'r7c7');
insert into grid(id, css_id) values(35, 'r7c8');
insert into grid(id, css_id) values(36, 'r7c9');
insert into grid(id, css_id) values(37, 'r7c10');
insert into grid(id, css_id) values(38, 'r7c11');
insert into grid(id, css_id) values(39, 'r7c12');
insert into grid(id, css_id) values(40, 'r8c6');
insert into grid(id, css_id) values(41, 'r8c7');
insert into grid(id, css_id) values(42, 'r8c8');
insert into grid(id, css_id) values(43, 'r8c9');
insert into grid(id, css_id) values(44, 'r8c10');


insert into phoneme_grid(phoneme_id, grid_id) values(38,0); 
insert into phoneme_grid(phoneme_id, grid_id) values(3,1);
insert into phoneme_grid(phoneme_id, grid_id) values(12,2);
insert into phoneme_grid(phoneme_id, grid_id) values(52,3);
insert into phoneme_grid(phoneme_id, grid_id) values(5,3);
insert into phoneme_grid(phoneme_id, grid_id) values(25,3);
insert into phoneme_grid(phoneme_id, grid_id) values(49,4);
insert into phoneme_grid(phoneme_id, grid_id) values(8,5);
insert into phoneme_grid(phoneme_id, grid_id) values(16,6);
insert into phoneme_grid(phoneme_id, grid_id) values(42,7);
insert into phoneme_grid(phoneme_id, grid_id) values(28,7);
insert into phoneme_grid(phoneme_id, grid_id) values(45,8);
insert into phoneme_grid(phoneme_id, grid_id) values(19,9);
insert into phoneme_grid(phoneme_id, grid_id) values(17,9);
insert into phoneme_grid(phoneme_id, grid_id) values(40,9);
insert into phoneme_grid(phoneme_id, grid_id) values(21,10);
insert into phoneme_grid(phoneme_id, grid_id) values(22,11);
insert into phoneme_grid(phoneme_id, grid_id) values(14,12);
insert into phoneme_grid(phoneme_id, grid_id) values(35,13);
insert into phoneme_grid(phoneme_id, grid_id) values(48,14);
insert into phoneme_grid(phoneme_id, grid_id) values(11,15);
insert into phoneme_grid(phoneme_id, grid_id) values(41,16);
insert into phoneme_grid(phoneme_id, grid_id) values(46,17);
insert into phoneme_grid(phoneme_id, grid_id) values(0,17);
insert into phoneme_grid(phoneme_id, grid_id) values(44,18);
insert into phoneme_grid(phoneme_id, grid_id) values(36,19);
insert into phoneme_grid(phoneme_id, grid_id) values(,20);
insert into phoneme_grid(phoneme_id, grid_id) values(2,21);
insert into phoneme_grid(phoneme_id, grid_id) values(23,22);
insert into phoneme_grid(phoneme_id, grid_id) values(9,22);
insert into phoneme_grid(phoneme_id, grid_id) values(4,23);
insert into phoneme_grid(phoneme_id, grid_id) values(6,24);
insert into phoneme_grid(phoneme_id, grid_id) values(30,25);
insert into phoneme_grid(phoneme_id, grid_id) values(39,26);
insert into phoneme_grid(phoneme_id, grid_id) values(32,27);
insert into phoneme_grid(phoneme_id, grid_id) values(34,28);
insert into phoneme_grid(phoneme_id, grid_id) values(10,29);
insert into phoneme_grid(phoneme_id, grid_id) values(1,30);
insert into phoneme_grid(phoneme_id, grid_id) values(15,31);
insert into phoneme_grid(phoneme_id, grid_id) values(,31);
insert into phoneme_grid(phoneme_id, grid_id) values(18,32);
insert into phoneme_grid(phoneme_id, grid_id) values(7,32);
insert into phoneme_grid(phoneme_id, grid_id) values(30,33);
insert into phoneme_grid(phoneme_id, grid_id) values(13,34);
insert into phoneme_grid(phoneme_id, grid_id) values(26,35);
insert into phoneme_grid(phoneme_id, grid_id) values(51,36);
insert into phoneme_grid(phoneme_id, grid_id) values(,37);
insert into phoneme_grid(phoneme_id, grid_id) values(47,38);
insert into phoneme_grid(phoneme_id, grid_id) values(20,39);
insert into phoneme_grid(phoneme_id, grid_id) values(31,40);
insert into phoneme_grid(phoneme_id, grid_id) values(29,41);
insert into phoneme_grid(phoneme_id, grid_id) values(43,42);
insert into phoneme_grid(phoneme_id, grid_id) values(37,43);
insert into phoneme_grid(phoneme_id, grid_id) values(50,44);

