

insert into grid(id, css_id) values(0, 'r1s4');
insert into grid(id, css_id) values(1, 'r1s12');
insert into grid(id, css_id) values(2, 'r2s4');
insert into grid(id, css_id) values(3, 'r2s5');
insert into grid(id, css_id) values(4, 'r2s11');
insert into grid(id, css_id) values(5, 'r2s12');
insert into grid(id, css_id) values(6, 'r3s4');
insert into grid(id, css_id) values(7, 'r3s5');
insert into grid(id, css_id) values(8, 'r3s10');
insert into grid(id, css_id) values(9, 'r3s11');
insert into grid(id, css_id) values(10,'r3s12');
insert into grid(id, css_id) values(11, 'r4s4');
insert into grid(id, css_id) values(12, 'r4s5');
insert into grid(id, css_id) values(13, 'r4s6');
insert into grid(id, css_id) values(14, 'r4s10');
insert into grid(id, css_id) values(15, 'r4s11');
insert into grid(id, css_id) values(16, 'r4s12');
insert into grid(id, css_id) values(17, 'r5s4');
insert into grid(id, css_id) values(18, 'r5s5');
insert into grid(id, css_id) values(19, 'r5s6');
insert into grid(id, css_id) values(20, 'r5s10');
insert into grid(id, css_id) values(21, 'r5s11');
insert into grid(id, css_id) values(22, 'r5s12');
insert into grid(id, css_id) values(23, 'r6s4');
insert into grid(id, css_id) values(24, 'r6s5');
insert into grid(id, css_id) values(25, 'r6s6');
insert into grid(id, css_id) values(26, 'r6s7');
insert into grid(id, css_id) values(27, 'r6s9');
insert into grid(id, css_id) values(28, 'r6s10');
insert into grid(id, css_id) values(29, 'r6s11');
insert into grid(id, css_id) values(30, 'r6s12');
insert into grid(id, css_id) values(31, 'r7s4');
insert into grid(id, css_id) values(32, 'r7s5');
insert into grid(id, css_id) values(33, 'r7s6');
insert into grid(id, css_id) values(34, 'r7s7');
insert into grid(id, css_id) values(35, 'r7s8');
insert into grid(id, css_id) values(36, 'r7s9');
insert into grid(id, css_id) values(37, 'r7s10');
insert into grid(id, css_id) values(38, 'r7s11');
insert into grid(id, css_id) values(39, 'r7s12');
insert into grid(id, css_id) values(40, 'r8s6');
insert into grid(id, css_id) values(41, 'r8s7');
insert into grid(id, css_id) values(42, 'r8s8');
insert into grid(id, css_id) values(43, 'r8s9');
insert into grid(id, css_id) values(44, 'r8s10');

